import { Database } from '@/lib/supabase/database.types'

type Turf = Omit<Database['public']['Tables']['turfs']['Row'], 'is_active'> & { is_active?: boolean }

export const STATIC_COIMBATORE_TURFS: Turf[] = [
  {
    id: 'static-1',
    owner_id: null,
    name: '433 Arena Turf',
    description: 'Premium football turf with top-grade artificial grass and floodlights. Located in the heart of Kuniyamuthur, perfect for evening matches and weekend tournaments.',
    location: { city: 'Coimbatore', address: 'Subbulakshmi Nagar, Rangsamy Naidu Nagar, Kuniyamuthur, Coimbatore', area: 'Kuniyamuthur' },
    coordinates: { lat: 10.9615, lng: 76.9558 },
    price_per_hour: 900,
    images: [
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
      'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=800&q=80',
    ],
    is_verified: true,
    is_premium: false,
    is_24hours: false,
    sports: ['Football'],
    timings: '5 AM - 11 PM',
    amenities: ['Floodlights', 'Parking', 'Drinking Water'],
    rating: 4.6,
    review_count: 312,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'static-2',
    owner_id: null,
    name: 'Kickoff Sports Arena',
    description: 'Open 24/7 multi-sport arena for football and cricket enthusiasts. Professional-grade turf with washroom facilities and ample parking.',
    location: { city: 'Coimbatore', address: 'P N Nagar, Kuniyamuthur, Coimbatore', area: 'Kuniyamuthur' },
    coordinates: { lat: 10.9572, lng: 76.9495 },
    price_per_hour: 1100,
    images: [
      'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800&q=80',
      'https://images.unsplash.com/photo-1510051640316-cee39563ddab?w=800&q=80',
    ],
    is_verified: true,
    is_premium: false,
    is_24hours: true,
    sports: ['Football', 'Cricket'],
    timings: '24 Hours',
    amenities: ['Floodlights', 'Parking', 'Washroom'],
    rating: 4.5,
    review_count: 187,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'static-3',
    owner_id: null,
    name: 'Ground Zero',
    description: 'One of the highest-rated football turfs in Coimbatore. Maintained to professional standards with excellent floodlighting for night games.',
    location: { city: 'Coimbatore', address: 'Rathinapuri, Kuniyamuthur, Coimbatore', area: 'Kuniyamuthur' },
    coordinates: { lat: 10.9548, lng: 76.9529 },
    price_per_hour: 1000,
    images: [
      'https://images.unsplash.com/photo-1471295253337-3ceaaedca402?w=800&q=80',
      'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
    ],
    is_verified: true,
    is_premium: false,
    is_24hours: false,
    sports: ['Football'],
    timings: '6 AM - 12 AM',
    amenities: ['Parking', 'Floodlights'],
    rating: 4.7,
    review_count: 543,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-03T00:00:00Z',
  },
  {
    id: 'static-4',
    owner_id: null,
    name: 'T&D Sports Arena',
    description: "Coimbatore's top-rated premium sports destination. Multi-sport facility with a cafe, flood-lit turf, and 24/7 operation — ideal for corporate events and tournaments.",
    location: { city: 'Coimbatore', address: 'Eachanari, Coimbatore', area: 'Eachanari' },
    coordinates: { lat: 10.9215, lng: 76.9737 },
    price_per_hour: 1800,
    images: [
      'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?w=800&q=80',
      'https://images.unsplash.com/photo-1518604964687-a0a3c3f42e2a?w=800&q=80',
    ],
    is_verified: true,
    is_premium: true,
    is_24hours: true,
    sports: ['Football', 'Cricket', 'Box Cricket'],
    timings: '24 Hours',
    amenities: ['Floodlights', 'Parking', 'Cafeteria', 'Washroom'],
    rating: 4.9,
    review_count: 891,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-04T00:00:00Z',
  },
  {
    id: 'static-5',
    owner_id: null,
    name: 'Manchester Sports Academy',
    description: 'Multi-sport academy with three dedicated courts for football, badminton, and box cricket. Professional coaching available on weekends.',
    location: { city: 'Coimbatore', address: 'Siruvani Main Road, Kalampalayam, Coimbatore', area: 'Kalampalayam' },
    coordinates: { lat: 10.9444, lng: 76.9207 },
    price_per_hour: 1500,
    images: [
      'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800&q=80',
      'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&q=80',
    ],
    is_verified: true,
    is_premium: true,
    is_24hours: false,
    sports: ['Football', 'Badminton', 'Box Cricket'],
    timings: '5 AM - 11 PM',
    amenities: ['Parking', 'Badminton Court', 'Floodlights'],
    rating: 4.5,
    review_count: 264,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'static-6',
    owner_id: null,
    name: '5th Yard Football Turf',
    description: 'Popular football turf in Peelamedu featuring gallery seating for spectators. Great for competitive matches and college tournaments.',
    location: { city: 'Coimbatore', address: 'Peelamedu, Coimbatore', area: 'Peelamedu' },
    coordinates: { lat: 11.0301, lng: 77.0023 },
    price_per_hour: 1300,
    images: [
      'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=800&q=80',
      'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
    ],
    is_verified: true,
    is_premium: false,
    is_24hours: false,
    sports: ['Football'],
    timings: '6 AM - 11 PM',
    amenities: ['Floodlights', 'Parking', 'Gallery Seating'],
    rating: 4.7,
    review_count: 428,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-06T00:00:00Z',
  },
  {
    id: 'static-7',
    owner_id: null,
    name: 'Wolfz Turf Cafe',
    description: 'Unique turf experience with an on-site cafe. Play football or cricket and unwind with food and drinks right after. A favourite hangout in Singanallur.',
    location: { city: 'Coimbatore', address: 'Singanallur, Coimbatore', area: 'Singanallur' },
    coordinates: { lat: 11.0012, lng: 77.0271 },
    price_per_hour: 1400,
    images: [
      'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80',
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
    ],
    is_verified: true,
    is_premium: false,
    is_24hours: false,
    sports: ['Football', 'Cricket'],
    timings: '5 AM - 12 AM',
    amenities: ['Cafe', 'Parking', 'Floodlights'],
    rating: 4.6,
    review_count: 156,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-07T00:00:00Z',
  },
  {
    id: 'static-8',
    owner_id: null,
    name: 'Nilgiri Football & Cricket Turf',
    description: 'Premium 24-hour turf in Saravanampatti with cafe, full washroom facilities, and spacious parking. One of the largest turf venues in Coimbatore.',
    location: { city: 'Coimbatore', address: 'Saravanampatti, Coimbatore', area: 'Saravanampatti' },
    coordinates: { lat: 11.0824, lng: 76.9991 },
    price_per_hour: 1700,
    images: [
      'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=800&q=80',
      'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800&q=80',
    ],
    is_verified: true,
    is_premium: true,
    is_24hours: true,
    sports: ['Football', 'Cricket'],
    timings: '24 Hours',
    amenities: ['Floodlights', 'Parking', 'Washroom', 'Cafe'],
    rating: 4.8,
    review_count: 674,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-08T00:00:00Z',
  },
  {
    id: 'static-9',
    owner_id: null,
    name: 'UFC Urban Football Club',
    description: 'Upscale football experience in RS Puram with premium seating and professional-grade turf. Ideal for corporate bookings and high-level tournaments.',
    location: { city: 'Coimbatore', address: 'RS Puram, Coimbatore', area: 'RS Puram' },
    coordinates: { lat: 11.0089, lng: 76.9514 },
    price_per_hour: 1600,
    images: [
      'https://images.unsplash.com/photo-1518604964687-a0a3c3f42e2a?w=800&q=80',
      'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?w=800&q=80',
    ],
    is_verified: true,
    is_premium: true,
    is_24hours: false,
    sports: ['Football'],
    timings: '6 AM - 11 PM',
    amenities: ['Floodlights', 'Premium Seating', 'Parking'],
    rating: 4.7,
    review_count: 339,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-09T00:00:00Z',
  },
  {
    id: 'static-10',
    owner_id: null,
    name: 'Turf Ten5',
    description: "Coimbatore's most premium turf experience on Avinashi Road. Luxury lounge, cafe, 24/7 operations, and state-of-the-art floodlights. The ultimate destination for serious players.",
    location: { city: 'Coimbatore', address: 'Avinashi Road, Coimbatore', area: 'Avinashi Road' },
    coordinates: { lat: 11.0408, lng: 77.0405 },
    price_per_hour: 2200,
    images: [
      'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
      'https://images.unsplash.com/photo-1471295253337-3ceaaedca402?w=800&q=80',
    ],
    is_verified: true,
    is_premium: true,
    is_24hours: true,
    sports: ['Football', 'Box Cricket'],
    timings: '24 Hours',
    amenities: ['Luxury Lounge', 'Parking', 'Floodlights', 'Cafe'],
    rating: 4.9,
    review_count: 1024,
    custom_commission_rate: null,
    razorpay_linked_account_id: null,
    created_at: '2026-01-10T00:00:00Z',
  },
]
